config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    get "/customers/my_page" => "customers#show"
    get "/customers/edit" => "customers#edit"
    patch "/customers" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    

    resources :items, only:[:index, :show]

    get "/cart_items" => "cart_items#index"
    patch "/cart_items/:id" => "cart_items#update", as: "cart_items_update"
    delete "/cart_items/destroyall" => "cart_items#destroyall", as: "cart_items_destroyall"
    delete "/cart_items/:id" => "cart_items#destroy", as: "cart_items_destroy"
    
    post "/cart_items" => "cart_items#create", as: 'cart_add'

    get "/orders/new" => "orders#new", as: 'orders_new'
    post "/orders/confirm" => "orders#confirm"
    #追加したところ
    get "/orders/confirm" => "orders#confirm"
    
    get "/orders/complete" => "orders#complete"
    post "/orders" => "orders#create"
    get "/orders" => "orders#index"
    get "/orders/:id" => "orders#show", as: 'order_detail'

    resources :addresses, only:[:index, :new, :edit, :create, :update, :destroy]

  end





  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  root to: 'homes#top'
  get "/about" => "homes#about"

  get "/admin" => "admin/homes#top"

  namespace :admin do
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_items, only:[:update]
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    customer = Customer.find(params[:id])
    customer.update(customer_params)
    redirect_to admin_customer_path(customer)
  end


  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_active)
  end

end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  def after_sign_up_path_for(resource)
    customers_my_page_path(current_customer.id)
  end
end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_inactive_user, only: [:create]


  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def reject_inactive_user
    @user = Customer.find_by(email: params[:customer][:email])
    if @user
      if @user.valid_password?(params[:customer][:password]) && !@user.is_active
        flash[:error] = "退会済みです。"
        redirect_to new_customer_session_path
      end
    end
  end
end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/admin/customers/edit.html.erb
<h1>admin顧客編集画面</h1>

  <div class="col-md-8 mx-auto">
    <div class ="row mb-3">
          <h4 class="text-center bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
    </div>

    <%= form_with model: @customer, url:admin_customer_path, local:true do |f| %>

      <table class ="table table-borderless">
          <tr>
            <th>会員ID</th><td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th></th><td><%= f.text_field :last_name %>　<%= f.text_field :first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th><td><%= f.text_field :last_name_kana %>　<%= f.text_field :first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th><td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th>住所</th><td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <th>電話番号</th><td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th><td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_active, :true, checked: true %>
              <%= f.label :is_active, '有効', value: 1 %>

              <%= f.radio_button :is_active, :false %>
              <%= f.label :is_active, '退会', value: 0 %>

            </td>
          </tr>

          <tr>
            <th></th>
            <td><%= f.submit '変更を保存', class: 'btn btn-success btn-lg' %></td>
          </tr>
      </table>

    <% end %>
  </div>

app/views/admin/customers/index.html.erb
<div class="col-md-8 mx-auto">
  <div class ="row mb-3">
      <h4 class="text-center bg-light">会員一覧</h4>
  </div>


  <table class ="table border-bottom">
    <thead class="thead-light">
      <tr　>
        <th style="width: 15%">会員ID</th>
        <th style="width: 45%">氏名</th>
        <th style="width: 20%">メールアドレス</th>
        <th style="width: 20%">ステータス</th>
      </tr>
    </thead>

    <tbody>
      <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.id %></td>
        <td>
          <%= link_to admin_customer_path(customer) do %>
              <%= customer.last_name %><%= customer.first_name %>
          <% end %>
        </td>
        <td><%= customer.email %></td>
        <td>
          
          <% if customer.is_active == true %>
            <p>有効</p>
          <% elsif customer.is_active == false  %>
            <p>退会</p>
          <% end %>

          </td>
      </tr>
      <% end %>
    </tbody>

  </table>
</div>

app/views/admin/customers/show.html.erb
<div class="col-md-8 mx-auto">
  <div class ="row mb-3">
      <h4 class="text-center bg-light"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h4>
  </div>


      <table class ="table table-borderless">
          <tr>
            <th>会員ID</th><td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th></th><td><%= @customer.last_name %>　<%= @customer.first_name %></td>
          </tr>
          <tr>
            <th>フリガナ</th><td><%= @customer.last_name_kana %>　<%= @customer.first_name_kana %></td>
          </tr>
          <tr>
            <th>郵便番号</th><td><%= @customer.postal_code %></td>
          </tr>
          <tr>
            <th>住所</th><td><%= @customer.address %></td>
          </tr>
          <tr>
            <th>電話番号</th><td><%= @customer.telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th><td><%= @customer.email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th><td><%= @customer.is_active %></td>
          </tr>

          <tr>
            <th></th>
            <td><%= link_to "編集する", edit_admin_customer_path(@customer), class: 'btn btn-success btn-md mr-5' %> <%= link_to "注文履歴一覧を見る", about_path, class: 'btn btn-primary btn-md' %></td>

          </tr>
      </table>

    </div>