config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    get "/customers/my_page" => "customers#show"
    get "/customers/edit" => "customers#edit"
    patch "/customers" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    

    resources :items, only:[:index, :show]

    get "/cart_items" => "cart_items#index"
    patch "/cart_items/:id" => "cart_items#update", as: "cart_items_update"
    delete "/cart_items/destroyall" => "cart_items#destroyall", as: "cart_items_destroyall"
    delete "/cart_items/:id" => "cart_items#destroy", as: "cart_items_destroy"
    
    post "/cart_items" => "cart_items#create", as: 'cart_add'

    get "/orders/new" => "orders#new", as: 'orders_new'
    post "/orders/confirm" => "orders#confirm"
    #追加したところ
    get "/orders/confirm" => "orders#confirm"
    
    get "/orders/complete" => "orders#complete"
    post "/orders" => "orders#create"
    get "/orders" => "orders#index"
    get "/orders/:id" => "orders#show", as: 'order_detail'

    resources :addresses, only:[:index, :new, :edit, :create, :update, :destroy]

  end





  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  root to: 'homes#top'
  get "/about" => "homes#about"

  get "/admin" => "admin/homes#top"

  namespace :admin do
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_items, only:[:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, through: :order_items
  
  #belongs_to :genre
  attachment :image
  
  ## 消費税を求めるメソッド
  def with_tax_price
      (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :items
  has_many :order_items



  enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  
  def index
  end
  
  def create
  end
  
  def edit
  end
  
  def update
  end
  
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  def top
    @orders = Order.all

  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.save!
    redirect_to admin_item_path(@item)
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to admin_item_path(item)
  end

  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  
  def show 
    @order = Order.find(params[:id])
    @order_items = @order.order_items
    
    
  end
  
  def update
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      root_path              #ここもpathはご自由に変更してください
    end
  end
  
  def
  after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order("id DESC")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/homes/top.html.erb
<div class="col-md-8 mx-auto mt-4">
    <div class ="d-flex justify-content-between mb-3">
        <div>
          <h4 class="text-center bg-light">注文履歴一覧</h4>
        </div>
    </div>



    <div class="row">
      <div class="col-md-10 ">
        <table class ="table table-bordered">
          <thead class="thead-light">
            <tr　>
              <th>購入日時</th>
              <th>購入者</th>
              <th>注文個数</th>

            </tr>
          </thead>

          <tbody >
            <% @orders.each do |order| %>
            <tr >
              <td>
                <%= link_to admin_order_path(order) do %>
                    <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S')  %>
                <% end %>

              </td>
              <td><%= order.customer.last_name %><%= order.customer.first_name %></td>
              <td>
                <% @sum=0 %>
                <% order.order_items.each do |item| %>
                  <% @sum += item.amount %>
                <% end %>
                <%= @sum %>
              </td>
            </tr>
            <% end %>
          </tbody>

        </table>
      </div>
    </_div>



</div>

app/views/homes/about.html.erb
<h1>Aboutページ</h1>

<div class="container">
  <div class="mx-auto text-center">

    <h1 class="mt-3 mb-3">About</h1>

    <p>
      ながのCAKEは全国発送可能なケーキ屋さんです。<br>
      お子様からお年寄りの方までお召し上がりいただけるよう、<br>
      様々なバリエーションをご用意しております。<br>
      また、全国へ発送可能ですので「いつ」でも「どこ」でもご注文いただけます。<br>
      ぜひご注文ください。
    </p>

  </div>
</div>

app/views/homes/top.html.erb
<div class="container ">

    <div class ="text-center">
        <p class ="border">
            ようこそ、ながのCAKEへ！<br>
            このサイトは、ケーキ販売のECサイトになります。<br>
            会員でない方も商品の閲覧はできますが、<br>購入には会員登録が必要になります。
        </p>
    </div>

    <div>
        <h1>新着商品</h1>
          <div class="row mx-auto">


              <% @items.each do |item| %>

              <div class="col">
                <%= link_to item_path(item) do %>
                  <%= attachment_image_tag item, :image, :fill, 200, 200, format: 'jpeg' %>
                <% end %>

                <p><%= item.name %></p>
                <p>¥<%= (item.price*1.1).floor %></p>
              </div>
              <% end %>


          </div>
    </div>

</div>