config/routes.rb
Rails.application.routes.draw do

  scope module: :public do
    get "/customers/my_page" => "customers#show"
    get "/customers/edit" => "customers#edit"
    patch "/customers" => "customers#update"
    get "/customers/unsubscribe" => "customers#unsubscribe"
    patch "/customers/withdraw" => "customers#withdraw"
    

    resources :items, only:[:index, :show]

    get "/cart_items" => "cart_items#index"
    patch "/cart_items/:id" => "cart_items#update", as: "cart_items_update"
    delete "/cart_items/destroyall" => "cart_items#destroyall", as: "cart_items_destroyall"
    delete "/cart_items/:id" => "cart_items#destroy", as: "cart_items_destroy"
    
    post "/cart_items" => "cart_items#create", as: 'cart_add'

    get "/orders/new" => "orders#new", as: 'orders_new'
    post "/orders/confirm" => "orders#confirm"
    #追加したところ
    get "/orders/confirm" => "orders#confirm"
    
    get "/orders/complete" => "orders#complete"
    post "/orders" => "orders#create"
    get "/orders" => "orders#index"
    get "/orders/:id" => "orders#show", as: 'order_detail'

    resources :addresses, only:[:index, :new, :edit, :create, :update, :destroy]

  end





  devise_for :admin, controllers: {
    sessions:      'admin/sessions',
    passwords:     'admin/passwords',
    registrations: 'admin/registrations'
  }

  devise_for :customers, controllers: {
      sessions:      'customers/sessions',
      passwords:     'customers/passwords',
      registrations: 'customers/registrations'
    }

  root to: 'homes#top'
  get "/about" => "homes#about"

  get "/admin" => "admin/homes#top"

  namespace :admin do
    resources :items, only:[:index, :new, :create, :show, :edit, :update]
    resources :genres, only:[:index, :create, :edit, :update]
    resources :customers, only:[:index, :show, :edit, :update]
    resources :orders, only:[:show, :update]
    resources :order_items, only:[:update]
  end

end

app/models/address.rb
class Address < ApplicationRecord

  belongs_to :customer

  def full_address
    '〒' + postal_code + ' ' + address + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  
  belongs_to :customer
  belongs_to :item
  
  ## 小計を求めるメソッド
  def subtotal
      item.with_tax_price * amount
  end
  
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy
  
  
end

app/models/genre.rb
class Genre < ApplicationRecord
  
  has_many :items, dependent: :destroy
  
end

app/models/item.rb
class Item < ApplicationRecord
  
  has_many :cart_items, dependent: :destroy
  has_many :orders, through: :order_items
  
  #belongs_to :genre
  attachment :image
  
  ## 消費税を求めるメソッド
  def with_tax_price
      (price * 1.1).floor
  end
  
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :items
  has_many :order_items



  enum payment_method: { credit_card: 0, transfer: 1 }

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :item
  belongs_to :order

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?
  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end

  def after_sign_in_path_for(resource)
    case resource
    when Admin
      admin_path          #pathは設定したい遷移先へのpathを指定してください
    when Customer
      root_path              #ここもpathはご自由に変更してください
    end
  end
  
  def
  after_sign_out_path_for(resource_or_scope)
      if resource_or_scope == :customer
          root_path
      elsif resource_or_scope == :admin
          new_admin_session_path
      else
          root_path
      end
  end


end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @items = Item.order("id DESC")
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_items_helper.rb
module Admin::OrderItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column vh-100">
    <header>
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">

          <a class="navbar-brand" href="/"><span>LOGO</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              <% if customer_signed_in? %>
                <!--ここから以下のログアウト以外は後ほど見直す必要あり-->
                <li class="nav-item"><!--マイページへのルーティング記載DONE -->
                  <%= link_to "マイページ", customers_my_page_path(current_customer.id), class: 'nav-link' %>
                </li>
                <li class="nav-item"><!--商品一覧へのルーティング記載DONE -->
                  <%= link_to "商品一覧", items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!--カートへのルーティング記載DONE -->
                  <%= link_to "カート", cart_items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!--ログアウトへのルーティング記載DONE -->
                  <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link' %>
                </li>

              <% elsif admin_signed_in? %>
                <!--ここから以下のログアウト以外は後ほど見直す必要あり-->
                <li class="nav-item"><!--マイページへのルーティング記載DONE -->
                  <%= link_to "商品一覧", admin_items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!--会員一覧へのルーティング記載 DONE -->
                  <%= link_to "会員一覧", admin_customers_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!--カートへのルーティング記載 -->
                  <%= link_to "注文履歴一覧", admin_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!--ログアウトへのルーティング記載DONE -->
                  <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link' %>
                </li>

              <% else %>
                <li class="nav-item"><!-- Aboutへのルーティング -->
                  <%= link_to "About", about_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!-- 商品一覧へのルーティング validationの設定する必要あり -->
                  <%= link_to "商品一覧", items_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!-- 新規登録へのルーティング -->
                  <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link' %>
                </li>
                <li class="nav-item"><!-- ログインへのルーティング -->
                  <%= link_to "ログイン", new_customer_session_path, class: 'nav-link' %>
                </li>

              <% end %>
            </ul>
          </div>

        </div>
      </nav>

    </header>

    <main>
      <%= yield %>
    </main>


    <footer>

    </footer>
  </body>
</html>